config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :discussions

  get "test_flash", to: "main#test_flash"

  # Defines the root path route ("/")
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: ->{ Current.user }

  validates :name, presence: true

  after_create_commit -> { broadcast_prepend_to "discussions" }
  after_update_commit -> { broadcast_replace_to "discussions" }
  after_destroy_commit -> { broadcast_remove_to "discussions" }

  def to_param
    "#{id}-#{name.downcase.to_s[0...100]}".parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true

  has_many :discussions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user, if: :user_signed_in?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def set_current_user
    Current.user = current_user
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  def index
    @discussions = Discussion.order(updated_at: :desc).all
  end

  def new
    @discussion = Discussion.new
  end

  def show

  end

  def create
    @discussion = Discussion.new(discussion_params)
    respond_to do |format|
      if @discussion.save
        format.html do
          redirect_to @discussion, notice: "discussion created"
        end
      else
        format.html do
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        @discussion.broadcast_replace(partial: "discussions/header", locals: {discussion: @discussion})
        format.html do
          redirect_to @discussion, notice: "discussion updated"
        end
      else
        format.html do
          render :edit, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @discussion.destroy!
    redirect_to discussions_path, notice: "discussion deleted"
  end

  private

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end

  def discussion_params
    params.require(:discussion).permit(:name, :closed, :pinned)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def test_flash
    flash.now[:notice] = "hello"
    flash.now[:alert] = "world"
    index
    render action: :index
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/discussions/_discussion.html.erb
<div id="<%= dom_id(discussion) %>" class="mb-2">
  <h2><%= link_to discussion.name, discussion_path(discussion) %></h2>
  Pinned: <%= discussion.pinned? %> | Closed: <%= discussion.closed? %>
  <div>
    <%= link_to "edit", edit_discussion_path(discussion) %> |
    <%= link_to "delete", discussion, data: { "turbo-method": :delete, "turbo-confirm": "sure?"} %>
  </div>
</div>

app/views/discussions/_form.html.erb
<%= form_with model: discussion do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize discussion.errors.count, "error" %></h2>
      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, placeholder: "Name...", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :pinned, class: "form-label" %>
    <%= form.check_box :pinned %>
  </div>

  <div class="mb-3">
    <%= form.label :closed, class: "form-label" %>
    <%= form.check_box :closed %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/discussions/_header.html.erb
<%= turbo_frame_tag dom_id(discussion) do  %>
  <div class="d-flex align-items-center justify-content-between">
    <div>
      <h1><%= discussion.name %></h1>
      <span class="text-muted fs-6">
        <% if discussion.pinned? %>
          <span class="badge rounded-pill bg-info">
            pinned
          </span>
        <% end %>
        <% if discussion.closed? %>
          <span class="badge rounded-pill text-danger">
            closed
          </span>
        <% end %>
      </span>
    </div>
    <div>
      <%= link_to "Edit", edit_discussion_path(discussion) %>
      <%= link_to "Destroy", discussion, data: {"turbo-method": :delete, "turbo-confirm": "are you sure?"} %>
    </div>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Edit discussion</h1>

<%= turbo_frame_tag dom_id(@discussion) do %>
  <%= render "form", discussion: @discussion %>
  <%= link_to "cancel", @discussion  %>
<% end %>

app/views/discussions/index.html.erb
<%= turbo_stream_from "discussions" %>
<div class="d-flex justify-content-between align-items-center">
  <h1>Discussion</h1>
  <%= link_to "New discussion", new_discussion_path, class: "btn btn-primary" %>
</div>

<div class="row mt-4">
  <div class="col">
    <div id="discussions">
      <%= render @discussions %>
    </div>
  </div>
</div>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render "form", discussion: @discussion %>

app/views/discussions/show.html.erb
<%= turbo_stream_from @discussion %>
<%= render partial: 'discussions/header', locals: { discussion: @discussion} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireForums</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container mt-4">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mb-4" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning mb-4" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <%= link_to "Hotwire Forums", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to "Discussion", discussions_path, class: "nav-item nav-link" %>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to Current.user.username, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sign out", destroy_user_session_path, class: "nav-item nav-link", data: { "turbo-method": :delete } %>
        <% else %>
          <%= link_to "New user", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login in", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>